feature/XTRF-1184: add events send by job offer app
xtrf/XTRFCloudInternalEventBus pull request #19
Opened 2021-10-11 07:53 UTC by czlowiek488

2021-10-11 07:59 UTC, wjarochowicz91 approved these changes

2021-10-19 14:25 UTC, bporebski commented on spec/TMSBusinessEvents.yaml
> +                      status:
rename status -> response

2021-11-17 13:10 UTC, bporebski commented on spec/TMSBusinessEvents.yaml
> +                  vendorId:
Ok

2021-11-17 13:10 UTC, bporebski commented on spec/TMSBusinessEvents.yaml
> +                  finisher:
W takim razie powinno pole nazywać się resolution zamiast finisher

2021-11-17 13:11 UTC, bporebski commented on spec/TMSBusinessEvents.yaml
> +                  selectionTrigger:
W porządku, niech tak zostanie

2021-11-17 13:24 UTC, bporebski commented on spec/TMSBusinessEvents.yaml
> +                      vendorId:
Xtrf powinien wysyłać, a następnie dostawać z powrotem taki obiekt, który jednoznacznie zidentyfikuje vendora

2021-11-17 13:57 UTC, bporebski commented
@czlowiek488 
Sorki za trochę opóźnioną wiadomość. Co do zmian:
Odpisałem w komentarzach na tematy, w których wymagane są jeszcze małe poprawki, tutaj jeszcze raz je wypisze:
- zmiana nazwy pola finisher -> resolution
- zamiast vendorId to obiekt vendor z takim samym schematem jak jest w JobOfferVendorDetails - w xtrfie będziemy wysyłać i chcieć odbierać taki obiekt, który jednoznacznie zidentyfikuje o którego vendora dokładnie chodzi. Aplikacja takich danych nie będzie potrzebować ale xtrf tak i powinien być taki obiekt być wysyłany w evencie job.offer.vendorSelectionRequested

Jeszcze co do pozostałych spraw:
1. co do punktu 2 z pierwszego mojego komentarza mam już odpowiedź co do pola finisher, jakie wartości powinien przyjmować:
automatic – when the action was triggered automatically by the Job Offers app
manual – when the action was triggered manually by the user on the Job Prospecting page
tms – when the action was triggered by an event from the TMS
zostało to też zaktualizowane w specyfikacji: https://coda.io/d/XTRF-Chat_d5OTAzFk1M7/Job-Offers-API_suksT#Events-sent-by-Job-Offers-app_turim
2. event job.offer.vendorResponded, co do pola response Boguś ma tutaj parę zastrzeżeń do waszej propozycji tych 4 statusów.
- negotiatedLowerOrEqual - czy negotiated equal to nie powinien być po prostu status accepted?
- negotiated higher/lower. Jeżeli vendor podda negocjacji plannedEndDate i poda krótszą datę ale stawkę da wyższą to to będzie negocjacja w górę czy w dół? I co jeśli w przyszłości będzie możliwość negocjacji innych pól i się to bardziej skomplikuje?
Propozycją Bogusia jest pozostanie przy typach: akceptacji, odrzucenia i negocjacji (ale bardzo ogólnie, bez wchodzenia w szczegóły)
3. dopytam jeszcze co do punktu 3 z poprzedniej wiadomości. Doszło do pomyłki, chodziło o dodanie tego pola do eventu job.offer.sentToVendor. Poza tym, czy potwierdzacie dodanie tego pola?

Daj znać czy wszystko jest ok z tymi uwagami.

2021-11-17 14:09 UTC, bporebski requested changes
@czlowiek488 
Sorki za trochę opóźnioną wiadomość. Co do zmian:
Odpisałem w komentarzach na tematy, w których wymagane są jeszcze małe poprawki, tutaj jeszcze raz je wypisze:

zmiana nazwy pola finisher -> resolution
zamiast vendorId to obiekt vendor z takim samym schematem jak jest w JobOfferVendorDetails - w xtrfie będziemy wysyłać i chcieć odbierać taki obiekt, który jednoznacznie zidentyfikuje o którego vendora dokładnie chodzi. Aplikacja takich danych nie będzie potrzebować ale xtrf tak i powinien być taki obiekt być wysyłany w evencie job.offer.vendorSelectionRequested
Jeszcze co do pozostałych spraw:

co do punktu 2 z pierwszego mojego komentarza mam już odpowiedź co do pola finisher, jakie wartości powinien przyjmować:
automatic – when the action was triggered automatically by the Job Offers app
manual – when the action was triggered manually by the user on the Job Prospecting page
tms – when the action was triggered by an event from the TMS
zostało to też zaktualizowane w specyfikacji na coda.io
event job.offer.vendorResponded, co do pola response Boguś ma tutaj parę zastrzeżeń do waszej propozycji tych 4 statusów.
negotiatedLowerOrEqual - czy negotiated equal to nie powinien być po prostu status accepted?
negotiated higher/lower. Jeżeli vendor podda negocjacji plannedEndDate i poda krótszą datę ale stawkę da wyższą to to będzie negocjacja w górę czy w dół? I co jeśli w przyszłości będzie możliwość negocjacji innych pól i się to bardziej skomplikuje?
Propozycją Bogusia jest pozostanie przy typach: akceptacji, odrzucenia i negocjacji (ale bardzo ogólnie, bez wchodzenia w szczegóły)
dopytam jeszcze co do punktu 3 z poprzedniej wiadomości. Doszło do pomyłki, chodziło o dodanie tego pola do eventu job.offer.sentToVendor. Poza tym, czy potwierdzacie dodanie tego pola?
Daj znać czy wszystko jest ok z tymi uwagami.

2022-03-02 15:18 UTC, bporebski commented
4 rzeczy do zmiany/dodania:
1. Pole chatUrl powinno być w evencie JobProspectingVendorSelectionRequestedEvent (komentarz)
2. zdefiniować nowy channel i pododawać te nowe eventy aby pojawiły się w wygenerowanej dokumentacji w menu nawigacyjnym (tak jak channel tms-events)
3. dodać pole trigger do eventu prospecting.cancelled
4. event prospecting.finished - resolution -> trigger - to pole przyjmujące jedną z wartości automatic, manual, tms. Dodatkowo w evencie powinno być zawarte pole resolution z wartością opisującą efekt zakończenia prospectingu

2022-03-02 18:14 UTC, bporebski approved these changes

2022-03-03 09:18 UTC, merged